### ISSUE TITLE
Web build breaks after bump to Expo 47

### ISSUE THREAD

**Issue by RobJacobson** [spirokit/expo-template-typescript#2]
This looks like a great project! The "out of the box" experience went flawlessly. I could spin up the sample template without any problems in both the Android emulator and React Web Native.

I then upgraded to Expo 47 using `expo-cli upgrade`. The Android build is continuing to work, but the web build breaks with many error messages in the browser console.

Could the template be updated to Expo 47, with these fixed? Thanks!

**Comment by mauro-codes** [comment]
Hey Rob! Thanks for all the detail about the issue. I'll take a look as soon as possible to see what's happening with the web build and SDK 47! Definitely wanted to do the upgrade :smile: Will keep you posted.

**Comment by mauro-codes** [comment]
All the available SpiroKit templates were upgraded to Expo SDK 47. Besides, a new version of SpiroKit (1.0.7) was released to address the issue with React Native Web 18, and it's already available on Gumroad. 

Now, this should work without problems.

Closing this issue. @RobJacobson Let me know how that goes.
