### ISSUE TITLE
Add Solito template?

### ISSUE THREAD

**Issue by RobJacobson** [spirokit/expo-template-typescript#3]
As a suggestion/feature request, could you please consider adding a template around the Solito framework/library? This uses Expo for Android and iOS development, while using Next.js for websites. (With the benefits of SSR, etc.)
https://solito.dev/

Spirokit seems like a natural UI kit for "single codebase" native/web development. FWIW, NativeBase has an existing Solito template, although it's several versions behind. They also seem to be leveraging Solito for their upcoming GlueStack framework. (They describe it as Expo + Next.js.)

**Comment by RobJacobson** [comment]
Awesome! You might also want to mention on the website that Spirokit is useful for website development, as well. I had to ask myself, "Can I use this for web?" before I reminded myself, "It's Expo."

**Comment by mauro-codes** [comment]
Quick update about this:
- I've been working on this request for the last few days. I already have a template working with Solito, Expo SDK 47 and NextJS 13.1 🎉 
- The remaining problem: There's no way to build the nextjs app on Vercel without adding the local tgz package to source control, which is not the best idea. I'll fix that problem by working on a private registry to host the SpiroKit package. In the meantime, I'll publish the template ASAP so you can start using it for local development.

**Comment by mauro-codes** [comment]
@RobJacobson I'm pleased to announce that the new "Universal app template" is available and ready to use after a few days of intense work. 😅

I also had to create my own "create-spirokit-app" CLI to simplify the process of creating new apps.

The official documentation will be updated soon, but in the meantime, you can visit this new repo where I'm migrating all the available templates, and there you will find the instructions:
[https://github.com/spirokit/templates](https://github.com/spirokit/templates).

I'll also release a small update to SpiroKit in the next few days with bug fixing for the web.

**Comment by RobJacobson** [comment]
Wonderful! I’m looking forward to giving it a try.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
